function [fitresult, gof,std95,ir] = createFit3(logws, lmpwrtf)
%CREATEFIT3(LOGWS,LMPWRTF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : logws
%      Y Output: lmpwrtf
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Dec-2019 15:34:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( logws, lmpwrtf );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
resid = yData -feval(fitresult,xData);
std95 = 2*std(resid);
ir = find(abs(resid) < std95);




